//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Dal.Aoe.Interfaces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tociEntities : DbContext
    {
        public tociEntities()
            : base("name=tociEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplyForm> ApplyForm { get; set; }
        public virtual DbSet<Apps> Apps { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Phrases> Phrases { get; set; }
        public virtual DbSet<Translations> Translations { get; set; }
        public virtual DbSet<ContactForm> ContactForm { get; set; }
      
    }
}
