//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingVsixOptions
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyForm
    {
        public int Id { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantSurname { get; set; }
        public string PhoneNumber { get; set; }
        public string ApplicantEmail { get; set; }
        public string Token { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
    }
}
