//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingVsixOptions
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tociEntities1 : DbContext
    {
        public tociEntities1()
            : base("name=tociEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplyForm> ApplyForms { get; set; }
        public virtual DbSet<App> Apps { get; set; }
        public virtual DbSet<ContactForm> ContactForms { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Phras> Phrases { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
    }
}
